services:
  - type: web
    name: decisio-backend
    runtime: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate && python manage.py install_pgvector && python manage.py collectstatic --noinput && python create_superuser.py
    startCommand: cd backend && gunicorn decisiobi.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.13"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "decisio-backend-846m.onrender.com"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: decisio-frontend
    runtime: node
    plan: free
    buildCommand: git submodule update --init --recursive && cd decision-spark && npm install && npm run build
    startCommand: cd decision-spark && node server-node.mjs
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3000"
      - key: VITE_API_BASE_URL
        value: ""
