# Generated by Django 6.0.3 on 2026-03-29 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for programmatic access', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('auto_resolve', models.BooleanField(default=False, help_text='Can system auto-resolve this?')),
                ('resolution_strategy', models.CharField(blank=True, help_text='default_value, majority_vote, latest_value', max_length=50, null=True)),
                ('icon', models.CharField(blank=True, help_text='UI icon for this conflict type', max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, help_text='UI color: #FF5733', max_length=7, null=True)),
                ('documentation_url', models.URLField(blank=True, help_text='Link to resolution guide', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conflict Type',
                'verbose_name_plural': 'Conflict Types',
                'db_table': 'conflits_conflicttype',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_table', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_columns', models.JSONField(default=list, help_text='List of column names involved')),
                ('affected_row_ids', models.JSONField(default=list, help_text='Row numbers or IDs involved')),
                ('conflict_details', models.JSONField(help_text='Specific conflict information')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('resolving', 'Resolving'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='detected', max_length=20)),
                ('priority', models.IntegerField(default=5, help_text='Priority 1-10 (manual override of severity)')),
                ('detected_by', models.CharField(default='system', help_text='system, user, api', max_length=50)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='SLA deadline', null=True)),
                ('recurrence_id', models.IntegerField(blank=True, help_text='Links recurring instances of same conflict', null=True)),
                ('impact_score', models.DecimalField(blank=True, decimal_places=2, help_text='Business impact 0-100', max_digits=5, null=True)),
                ('estimated_resolution_time', models.IntegerField(blank=True, help_text='Estimated resolution time in minutes', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, help_text='How was it resolved?', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_conflicts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conflicts', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ingestion.datasource')),
                ('parent_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_conflicts', to='conflits.conflict')),
                ('conflict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='conflits.conflicttype')),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflicts',
                'db_table': 'conflits_conflict',
                'ordering': ['-priority', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_method', models.CharField(choices=[('manual_override', 'Manual Override'), ('auto_merge', 'Auto Merge'), ('default_value', 'Use Default Value'), ('user_selected', 'User Selected'), ('majority_vote', 'Majority Vote'), ('latest_value', 'Latest Value'), ('discard', 'Discard Invalid Data')], max_length=50)),
                ('chosen_value', models.JSONField(blank=True, help_text='What value was chosen?', null=True)),
                ('alternative_values', models.JSONField(blank=True, help_text='What were the options?', null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in this resolution 0-100', max_digits=5, null=True)),
                ('is_reversible', models.BooleanField(default=True, help_text='Can we undo this if wrong?')),
                ('rollback_data', models.JSONField(blank=True, help_text='What to restore if rolled back?', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False, help_text='Needs manager approval?')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resolutions', to=settings.AUTH_USER_MODEL)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='conflits.conflict')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resolutions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflict Resolution',
                'verbose_name_plural': 'Conflict Resolutions',
                'db_table': 'conflits_conflictresolution',
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['status'], name='conflits_co_status_4fdfc7_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['detected_at'], name='conflits_co_detecte_bf2245_idx'),
        ),
    ]
