# Generated by Django 6.0.3 on 2026-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflits', '0002_systemconfig_activitylog_scheduledjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='group_name',
            field=models.CharField(blank=True, help_text='User-defined group label for batch operations', max_length=200, null=True),
        ),
    ]
