# Generated by Django 6.0.3 on 2026-05-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonnes_tableau', models.JSONField(default=list, help_text='Liste ordonnée des colonnes affichées')),
                ('kpis_visibles', models.JSONField(default=list, help_text='Liste des KPI affichés sur le dashboard')),
                ('kpis_ordre', models.JSONField(default=list, help_text="Ordre d'affichage des KPI cards")),
                ('layout_dashboard', models.JSONField(default=dict, help_text='Configuration de la disposition des widgets')),
                ('periode_defaut', models.CharField(choices=[('mois_en_cours', 'Mois en cours'), ('trimestre_en_cours', 'Trimestre en cours'), ('annee_en_cours', 'Année en cours'), ('30_derniers_jours', '30 derniers jours'), ('personnalise', 'Période personnalisée')], default='mois_en_cours', max_length=20)),
                ('devise', models.CharField(default='FCFA', max_length=5)),
                ('format_nombres', models.CharField(choices=[('fr-FR', 'Français (1 740 000)'), ('en-US', 'Anglais (1,740,000)')], default='fr-FR', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
            },
        ),
        migrations.CreateModel(
            name='VuePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📊', max_length=10)),
                ('config', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_partagee', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue personnalisée',
                'ordering': ['ordre', 'nom'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ordre__lte', 20)), name='max_vues_par_utilisateur')],
            },
        ),
    ]
