# Generated by Django 6.0.3 on 2026-03-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code: REV_Q1, CHURN_RATE', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(help_text='SQL expression or Python code')),
                ('formula_type', models.CharField(choices=[('sql', 'SQL Expression'), ('python', 'Python Code'), ('excel', 'Excel Formula')], default='sql', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('operator', models.CharField(blank=True, choices=[('>=', 'Greater than or equal'), ('<=', 'Less than or equal'), ('=', 'Equals'), ('>', 'Greater than'), ('<', 'Less than')], max_length=2, null=True)),
                ('unit', models.CharField(blank=True, help_text='%, $, units, hours, etc.', max_length=50, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Financial, Operational, Customer, etc.', max_length=100, null=True)),
                ('source_table', models.CharField(blank=True, max_length=100, null=True)),
                ('measure_column', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension_columns', models.JSONField(blank=True, default=list, help_text='Group by fields')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, help_text='WHERE clauses')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('aggregation_method', models.CharField(blank=True, help_text='SUM, AVG, COUNT, MIN, MAX', max_length=20, null=True)),
                ('benchmark_source', models.CharField(blank=True, help_text='Industry benchmark', max_length=100, null=True)),
                ('visualization_type', models.CharField(blank=True, help_text='gauge, trend, bar', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_kpis', to=settings.AUTH_USER_MODEL)),
                ('parent_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_kpis', to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'db_table': 'kpi_kpi',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('threshold_breach', 'Threshold Breach'), ('anomaly', 'Anomaly Detection'), ('scheduled', 'Scheduled Report')], max_length=20)),
                ('condition_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('equals', 'Equals'), ('changed_by', 'Changed By %')], max_length=10)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('threshold_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notification_channels', models.JSONField(default=list, help_text="['email', 'slack', 'sms', 'webhook']")),
                ('recipients', models.JSONField(default=list, help_text='List of user IDs or emails')),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('message_template', models.TextField(blank=True, help_text='Custom alert message', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('trigger_count', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Minutes between alerts')),
                ('mute_until', models.DateTimeField(blank=True, help_text='Temporarily disable', null=True)),
                ('escalation_policy', models.JSONField(blank=True, default=dict, help_text='If not acknowledged in X hours')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_kpi_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_kpi_alerts', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'KPI Alert',
                'verbose_name_plural': 'KPI Alerts',
                'db_table': 'kpi_kpialert',
                'ordering': ['-is_active', 'alert_name'],
            },
        ),
        migrations.CreateModel(
            name='KPICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(blank=True, help_text='Q1 2026, January 2026', max_length=100, null=True)),
                ('calculated_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('variance_absolute', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_variance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('on_target', 'On Target'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='By region, product, etc.')),
                ('calculation_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('estimated', 'Estimated')], default='automatic', max_length=20)),
                ('data_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rows_processed', models.IntegerField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Manual adjustments?', null=True)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('confidence_interval', models.JSONField(blank=True, default=list, help_text='[lower_bound, upper_bound]')),
                ('anomaly_detected', models.BooleanField(default=False, help_text='Is this value unusual?')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_kpi_calcs', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'KPI Calculation',
                'verbose_name_plural': 'KPI Calculations',
                'db_table': 'kpi_kpicalculation',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['kpi', 'period_start'], name='kpi_kpicalc_kpi_id_be3e79_idx')],
                'unique_together': {('kpi', 'period_start', 'period_end')},
            },
        ),
    ]
