# Generated by Django 6.0.3 on 2026-05-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usernotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='auth_userno_user_id_34082c_idx',
            old_name='auth_userno_user_id_8f52ec_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='auth_userno_user_id_93d288_idx',
            old_name='auth_userno_user_id_7eb61c_idx',
        ),
    ]
