# Generated by Django 6.0.3 on 2026-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
    ]
