# Generated by Django 6.0.3 on 2026-03-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('trend_analysis', 'Trend Analysis'), ('pattern_detection', 'Pattern Detection'), ('correlation', 'Correlation Analysis'), ('root_cause', 'Root Cause Analysis'), ('forecasting', 'Forecasting'), ('summary', 'Data Summary')], max_length=50)),
                ('prompt', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Relevant data snippets sent to AI')),
                ('model_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google AI'), ('azure', 'Azure OpenAI'), ('local', 'Local Model')], max_length=50)),
                ('model_name', models.CharField(help_text='gpt-4, claude-3, etc.', max_length=100)),
                ('model_parameters', models.JSONField(blank=True, default=dict, help_text='temperature, max_tokens, etc.')),
                ('response', models.TextField(blank=True, null=True)),
                ('response_html', models.TextField(blank=True, help_text='Formatted HTML version', null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('citations', models.JSONField(blank=True, default=list, help_text='Data points referenced by AI')),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dashboard')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.datasource')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.kpi')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ia_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('pattern', 'Pattern'), ('correlation', 'Correlation'), ('recommendation', 'Recommendation'), ('warning', 'Warning'), ('opportunity', 'Opportunity')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20, null=True)),
                ('supporting_data', models.JSONField()),
                ('affected_metrics', models.JSONField(blank=True, default=list)),
                ('affected_dimensions', models.JSONField(blank=True, default=dict)),
                ('statistical_significance', models.DecimalField(blank=True, decimal_places=4, help_text='p-value', max_digits=5, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('estimated_impact', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('urgency', models.CharField(blank=True, choices=[('immediate', 'Immediate Action Required'), ('soon', 'Action Soon'), ('optional', 'Optional')], max_length=20, null=True)),
                ('visualization_type', models.CharField(blank=True, choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('scatter_plot', 'Scatter Plot'), ('table', 'Table'), ('metric', 'Metric Card'), (None, 'None')], max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_reason', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Insight shelf-life', null=True)),
                ('auto_generated_report', models.BooleanField(default=False, help_text='Include in automated reports?')),
                ('shared_with', models.JSONField(blank=True, default=list, help_text="User IDs who've seen this")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ia_interpretation.aianalysis')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_insights', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'db_table': 'ia_insight',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['requested_by', 'created_at'], name='ia_analysis_request_4b520c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['analysis', 'insight_type'], name='ia_insight_analysi_4b953d_idx'),
        ),
    ]
