from django.db import models
from django.contrib.auth.models import User


class AIAnalysis(models.Model):
    """
    AI-powered analysis sessions using LLM models.
    Stores prompts, responses, and insights generated by AI.
    """
    ANALYSIS_TYPE_CHOICES = [
        ('trend_analysis', 'Trend Analysis'),
        ('pattern_detection', 'Pattern Detection'),
        ('correlation', 'Correlation Analysis'),
        ('root_cause', 'Root Cause Analysis'),
        ('forecasting', 'Forecasting'),
        ('summary', 'Data Summary'),
    ]
    
    MODEL_PROVIDER_CHOICES = [
        ('openai', 'OpenAI'),
        ('anthropic', 'Anthropic'),
        ('google', 'Google AI'),
        ('azure', 'Azure OpenAI'),
        ('local', 'Local Model'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
    ]
    
    # Context
    data_source = models.ForeignKey('ingestion.DataSource', on_delete=models.SET_NULL, null=True, blank=True)
    kpi = models.ForeignKey('kpi.KPI', on_delete=models.SET_NULL, null=True, blank=True)
    dashboard = models.ForeignKey('dashboard.Dashboard', on_delete=models.SET_NULL, null=True, blank=True)
    
    # Analysis request
    analysis_type = models.CharField(max_length=50, choices=ANALYSIS_TYPE_CHOICES)
    prompt = models.TextField()
    context_data = models.JSONField(default=dict, blank=True, help_text="Relevant data snippets sent to AI")
    
    # AI Model configuration
    model_provider = models.CharField(max_length=50, choices=MODEL_PROVIDER_CHOICES)
    model_name = models.CharField(max_length=100, help_text="gpt-4, claude-3, etc.")
    model_parameters = models.JSONField(default=dict, blank=True, help_text="temperature, max_tokens, etc.")
    
    # Response
    response = models.TextField(blank=True, null=True)
    response_html = models.TextField(blank=True, null=True, help_text="Formatted HTML version")
    confidence_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    citations = models.JSONField(default=list, blank=True, help_text="Data points referenced by AI")
    
    # Execution details
    tokens_used = models.IntegerField(null=True, blank=True)
    processing_time_ms = models.IntegerField(null=True, blank=True)
    cost_usd = models.DecimalField(max_digits=10, decimal_places=4, null=True, blank=True)
    
    # State
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    error_message = models.TextField(blank=True, null=True)
    retry_count = models.IntegerField(default=0)
    
    requested_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ai_analyses')
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.get_analysis_type_display()} - {self.prompt[:50]}"
    
    class Meta:
        db_table = 'ia_analysis'
        verbose_name = 'AI Analysis'
        verbose_name_plural = 'AI Analyses'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['requested_by', 'created_at']),
        ]


class AIInsight(models.Model):
    """
    Individual insights extracted from AI analyses.
    Categorized, actionable findings with supporting data.
    """
    INSIGHT_TYPE_CHOICES = [
        ('trend', 'Trend'),
        ('anomaly', 'Anomaly'),
        ('pattern', 'Pattern'),
        ('correlation', 'Correlation'),
        ('recommendation', 'Recommendation'),
        ('warning', 'Warning'),
        ('opportunity', 'Opportunity'),
    ]
    
    SEVERITY_CHOICES = [
        ('critical', 'Critical'),
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
        ('info', 'Info'),
    ]
    
    URGENCY_CHOICES = [
        ('immediate', 'Immediate Action Required'),
        ('soon', 'Action Soon'),
        ('optional', 'Optional'),
    ]
    
    VIZ_TYPE_CHOICES = [
        ('line_chart', 'Line Chart'),
        ('bar_chart', 'Bar Chart'),
        ('scatter_plot', 'Scatter Plot'),
        ('table', 'Table'),
        ('metric', 'Metric Card'),
        (None, 'None'),
    ]
    
    analysis = models.ForeignKey(AIAnalysis, on_delete=models.CASCADE, related_name='insights')
    insight_type = models.CharField(max_length=50, choices=INSIGHT_TYPE_CHOICES)
    
    # Content
    title = models.CharField(max_length=500)
    description = models.TextField()
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, null=True, blank=True)
    
    # Data backing
    supporting_data = models.JSONField()
    affected_metrics = models.JSONField(default=list, blank=True)
    affected_dimensions = models.JSONField(default=dict, blank=True)
    statistical_significance = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True, help_text="p-value")
    
    # Actionability
    recommended_action = models.TextField(blank=True, null=True)
    estimated_impact = models.DecimalField(max_digits=20, decimal_places=4, null=True, blank=True)
    urgency = models.CharField(max_length=20, choices=URGENCY_CHOICES, null=True, blank=True)
    
    # Presentation
    visualization_type = models.CharField(max_length=50, choices=VIZ_TYPE_CHOICES, null=True, blank=True)
    icon = models.CharField(max_length=50, blank=True, null=True)
    color_code = models.CharField(max_length=7, blank=True, null=True)
    
    # State
    is_verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='verified_insights')
    is_dismissed = models.BooleanField(default=False)
    dismissed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='dismissed_insights')
    dismissed_reason = models.TextField(blank=True, null=True)
    
    # Advanced features
    expires_at = models.DateTimeField(null=True, blank=True, help_text="Insight shelf-life")
    auto_generated_report = models.BooleanField(default=False, help_text="Include in automated reports?")
    shared_with = models.JSONField(default=list, blank=True, help_text="User IDs who've seen this")
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'ia_insight'
        verbose_name = 'AI Insight'
        verbose_name_plural = 'AI Insights'
        ordering = ['-severity', '-created_at']
        indexes = [
            models.Index(fields=['analysis', 'insight_type']),
        ]
