# Generated by Django 6.0.3 on 2026-03-29 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('remove_nulls', 'Remove Null Values'), ('fill_mean', 'Fill with Mean'), ('fill_median', 'Fill with Median'), ('fill_mode', 'Fill with Mode'), ('fill_value', 'Fill with Custom Value'), ('standardize', 'Standardize Format'), ('regex_replace', 'Regex Replace'), ('remove_duplicates', 'Remove Duplicates'), ('normalize', 'Normalize Values'), ('validate_format', 'Validate Format')], max_length=50)),
                ('column_pattern', models.CharField(blank=True, help_text='Regex pattern for column matching', max_length=200, null=True)),
                ('column_names', models.JSONField(blank=True, default=list, help_text='Specific column names to apply rule to')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Rule-specific configuration parameters')),
                ('priority', models.IntegerField(default=5, help_text='Execution priority (1-10, higher = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_all', models.BooleanField(default=False, help_text='Auto-apply to all new data sources')),
                ('category', models.CharField(blank=True, help_text='Grouping: formatting, validation, imputation', max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.IntegerField(default=1)),
                ('execution_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='nettoyage.cleaningrule')),
            ],
            options={
                'verbose_name': 'Cleaning Rule',
                'verbose_name_plural': 'Cleaning Rules',
                'db_table': 'nettoyage_cleaningrule',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_affected', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('log_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('batch_size', models.IntegerField(default=1000)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When should it run?', null=True)),
                ('worker_id', models.CharField(blank=True, help_text='Which worker processed this?', max_length=100, null=True)),
                ('memory_usage_mb', models.IntegerField(blank=True, help_text='Peak memory usage', null=True)),
                ('cpu_time_ms', models.IntegerField(blank=True, help_text='CPU time consumed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='ingestion.datasource')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='nettoyage.cleaningrule')),
            ],
            options={
                'verbose_name': 'Cleaning Job',
                'verbose_name_plural': 'Cleaning Jobs',
                'db_table': 'nettoyage_cleaningjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Cleaned row data as JSON object')),
                ('changes_made', models.JSONField(default=list, help_text='List of transformations applied')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Data quality score 0-100', max_digits=5, null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Has human validated this?')),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('export_path', models.CharField(blank=True, help_text='Where exported cleaned data?', max_length=500, null=True)),
                ('cleaned_at', models.DateTimeField(auto_now_add=True)),
                ('original_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_versions', to='ingestion.rawdata')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_cleaned_data', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_results', to='nettoyage.cleaningjob')),
            ],
            options={
                'verbose_name': 'Cleaned Data',
                'verbose_name_plural': 'Cleaned Data',
                'db_table': 'nettoyage_cleaneddata',
                'indexes': [models.Index(fields=['job', 'original_data'], name='nettoyage_c_job_id_bc7206_idx')],
                'unique_together': {('job', 'original_data')},
            },
        ),
    ]
