# Generated by Django 6.0.3 on 2026-03-30 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type_scope', models.CharField(blank=True, help_text='Optional source type filter', max_length=20, null=True)),
                ('quality_gate', models.JSONField(blank=True, default=dict, help_text='Thresholds such as min_quality_score')),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_pipelines', to=settings.AUTH_USER_MODEL)),
                ('rules', models.ManyToManyField(blank=True, related_name='pipelines', to='nettoyage.cleaningrule')),
            ],
            options={
                'verbose_name': 'Cleaning Pipeline',
                'verbose_name_plural': 'Cleaning Pipelines',
                'db_table': 'nettoyage_cleaningpipeline',
                'ordering': ['name'],
            },
        ),
    ]
