# Generated by Django 6.0.3 on 2026-04-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0004_alter_cleaningrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningjob',
            name='is_auto_triggered',
            field=models.BooleanField(default=False, help_text='Was this cleaning triggered automatically after upload?'),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='nettoyage.cleaningrule'),
        ),
    ]
