# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0005_add_auto_clean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningjob',
            name='export_path',
            field=models.CharField(
                blank=True,
                help_text='Latest exported file path',
                max_length=500,
                null=True,
            ),
        ),
    ]
