# Generated by Django 6.0.3 on 2026-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0011_add_cell_level_rule_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cleaningrun',
            new_name='nettoyage_c_source__641201_idx',
            old_name='nettoyage_cl_source__idx',
        ),
        migrations.RenameIndex(
            model_name='cleaningrun',
            new_name='nettoyage_c_method__e01f7b_idx',
            old_name='nettoyage_cl_method__idx',
        ),
        migrations.RenameIndex(
            model_name='correctionexample',
            new_name='nettoyage_c_correct_f3db95_idx',
            old_name='nettoyage_co_correcti_idx',
        ),
        migrations.RenameIndex(
            model_name='correctionexample',
            new_name='nettoyage_c_source__6b23ca_idx',
            old_name='nettoyage_co_source__idx',
        ),
        migrations.RenameIndex(
            model_name='rawstructuralsnapshot',
            new_name='nettoyage_r_source__c4e3ca_idx',
            old_name='nettoyage_ra_source__idx',
        ),
        migrations.AlterField(
            model_name='correctionexample',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='pgvector embedding of the structural fingerprint (all-MiniLM-L6-v2)', null=True),
        ),
        migrations.AlterField(
            model_name='rawstructuralsnapshot',
            name='column_types',
            field=models.JSONField(blank=True, default=dict, help_text='Per-column detected types {col_name: type}'),
        ),
        migrations.AlterField(
            model_name='rawstructuralsnapshot',
            name='merged_cells',
            field=models.JSONField(blank=True, default=list, help_text='List of merged cell ranges [{start_row, start_col, end_row, end_col}]'),
        ),
    ]
