# Generated by Django 6.0.3 on 2026-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0012_rename_nettoyage_cl_source__idx_nettoyage_c_source__641201_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrule',
            name='rule_type',
            field=models.CharField(choices=[('remove_nulls', 'Remove Null Values'), ('remove_empty_rows', 'Remove Empty or Whitespace Rows'), ('drop_rows_by_missing_threshold', 'Drop Rows by Missing Threshold'), ('drop_columns_by_missing_threshold', 'Drop Columns by Missing Threshold'), ('fill_mean', 'Fill with Mean'), ('fill_median', 'Fill with Median'), ('fill_mode', 'Fill with Mode'), ('fill_value', 'Fill with Custom Value'), ('standardize', 'Standardize Format'), ('regex_replace', 'Regex Replace'), ('remove_duplicates', 'Remove Duplicates'), ('normalize', 'Normalize Values'), ('convert_dtype', 'Convert Data Type'), ('value_map', 'Map Values'), ('rename_columns', 'Rename Columns'), ('split_column', 'Split Column'), ('merge_columns', 'Merge Columns'), ('validate_format', 'Validate Format'), ('extract_labeled_fields', 'Extract Labeled Fields from Text'), ('fix_ambiguous_chars', 'Fix Ambiguous Characters'), ('split_value_unit', 'Split Value and Unit'), ('explode_delimited_list', 'Explode Delimited List'), ('unpivot', 'Unpivot / Melt Crosstab')], max_length=50),
        ),
    ]
