# Generated by Django 6.0.3 on 2026-03-29 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('session_name', models.CharField(blank=True, help_text='User-friendly name', max_length=200, null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Conversation state, variables')),
                ('active_data_sources', models.JSONField(blank=True, default=list)),
                ('active_kpis', models.JSONField(blank=True, default=list)),
                ('bot_personality', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('concise', 'Concise'), ('detailed', 'Detailed')], default='professional', max_length=50)),
                ('language_preference', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(blank=True, choices=[('web', 'Web Interface'), ('mobile', 'Mobile App'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('resolution_achieved', models.BooleanField(default=False, help_text='Did bot help solve problem?')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Conversation topics')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chatbot_chatsession',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], max_length=10)),
                ('content_type', models.CharField(blank=True, choices=[('text', 'Text'), ('question', 'Question'), ('chart', 'Chart'), ('table', 'Table'), ('insight', 'Insight'), ('action', 'Action Button')], max_length=20, null=True)),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True, null=True)),
                ('markdown_content', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, help_text='QUERY_KPI, ASK_DATA, etc.', max_length=100, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('frustrated', 'Frustrated')], max_length=20, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('fallback_used', models.BooleanField(default=False, help_text='Did NLP fail?')),
                ('attached_chart', models.JSONField(blank=True, default=dict)),
                ('attached_data', models.JSONField(blank=True, default=dict)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatbot.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chatbot_chatmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(choices=[('data_query', 'Data Query'), ('kpi_query', 'KPI Query'), ('insight_request', 'Insight Request'), ('how_to', 'How To Question'), ('bug_report', 'Bug Report')], max_length=50)),
                ('parsed_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_entities', models.JSONField(blank=True, default=dict)),
                ('nlp_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('execution_plan', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('rows_returned', models.IntegerField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('full_result', models.JSONField(blank=True, null=True)),
                ('result_cached', models.BooleanField(default=False)),
                ('cache_key', models.CharField(blank=True, max_length=100, null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_satisfaction', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('is_training_example', models.BooleanField(default=False, help_text='Use for ML training?')),
                ('improved_response', models.TextField(blank=True, help_text='Human-edited better response', null=True)),
                ('similar_queries', models.JSONField(blank=True, default=list, help_text='Links to paraphrases')),
                ('complexity_score', models.IntegerField(blank=True, help_text='How complex was this query?', null=True)),
                ('requires_human', models.BooleanField(default=False, help_text='Flag for human review?')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_queries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query History',
                'verbose_name_plural': 'Query Histories',
                'db_table': 'chatbot_queryhistory',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_cha_user_id_9fd70b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_token'], name='chatbot_cha_session_18ba07_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='chatbot_cha_message_008306_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['intent'], name='chatbot_cha_intent_8c32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['user', 'executed_at'], name='chatbot_que_user_id_6591cd_idx'),
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['query_type'], name='chatbot_que_query_t_e91bda_idx'),
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['parsed_intent'], name='chatbot_que_parsed__138527_idx'),
        ),
    ]
