"""
Django settings for decisiobi project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

try:
    import certifi
except Exception:  # pragma: no cover
    certifi = None

# Load environment variables from .env file
load_dotenv()


def _split_csv_env(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]

if certifi is not None:
    os.environ.setdefault('SSL_CERT_FILE', certifi.where())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = _split_csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')
for local_host in ('testserver',):
    if local_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_host)


# Application definition

INSTALLED_APPS = [
    # Apps par défaut de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliothèques tierces (à installer via pip)
    'rest_framework',          # Pour créer ton API
    'rest_framework_simplejwt',  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',             # Pour autoriser React à parler au Backend

    # Tes 9 modules (Apps locales)
    'apps.authentication',     # M9: Auth JWT + RBAC
    'apps.ingestion',          # M1: Import fichiers
    'apps.nettoyage',           # M2: Nettoyage Pandas
    'apps.conflits',           # M3: Résolution conflits
    'apps.kpi',                # M4: Calcul KPI
    'apps.dashboard',          # M5: Dashboard
    'apps.ia_interpretation',  # M6: LLM API
    'apps.anomalies',          # M7: Isolation Forest
    'apps.chatbot',            # M8: NLP
    'apps.notifications',      # Notifications & Reporting
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware for frontend access
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Settings - Allow frontend to access API
DEFAULT_CORS_ALLOWED_ORIGINS = ",".join(
    [
        "http://localhost:3000",  # React default
        "http://localhost:5173",  # Vite default
        "http://localhost:8080",  # decision-spark local
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8080",
    ]
)

CORS_ALLOWED_ORIGINS = _split_csv_env(
    'CORS_ALLOWED_ORIGINS',
    DEFAULT_CORS_ALLOWED_ORIGINS,
)

# Or allow all origins during development (not recommended for production)
CORS_ALLOW_ALL_ORIGINS = DEBUG

ROOT_URLCONF = 'decisiobi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'decisiobi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'decisio_db'),
        'USER': os.getenv('DB_USER', 'decisio_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production collectstatic
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Additional static files directory
] if (BASE_DIR / 'static').exists() else []

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Time zone (adjust as needed)
TIME_ZONE = 'UTC'  # Change to your preferred timezone, e.g., 'Europe/Paris'


# ==================== REST FRAMEWORK CONFIGURATION ====================
REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.authentication.authentication.APITokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # Permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# ==================== JWT CONFIGURATION ====================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# ==================== M6 — Groq (interpretation KPI) ====================
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_KPI_MODEL = os.getenv('GROQ_KPI_MODEL', 'llama-3.3-70b-versatile')


# ==================== Email / Password reset ====================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@decisiobi.local')
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')


# ==================== Celery Beat (Scheduled Tasks) ====================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Douala'

CELERY_BEAT_SCHEDULE = {
    'check-scheduled-reports': {
        'task': 'apps.notifications.tasks.check_and_run_scheduled_reports',
        'schedule': 300.0,  # Every 5 minutes
    },
}

# ==================== STRUCTURE DETECTION (M2 Enhancement) ====================
STRUCTURE_DETECTION_CONFIDENCE_THRESHOLD = float(os.getenv('STRUCTURE_DETECTION_CONFIDENCE_THRESHOLD', '0.8'))
STRUCTURE_DETECTION_LLM_MODEL = os.getenv('STRUCTURE_DETECTION_LLM_MODEL', 'llama-3.3-70b-versatile')
STRUCTURE_DETECTION_EMBEDDING_MODEL = os.getenv('STRUCTURE_DETECTION_EMBEDDING_MODEL', 'all-MiniLM-L6-v2')
