# Generated by Django 6.0.3 on 2026-03-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel File'), ('api', 'API Connection'), ('database', 'Database'), ('json', 'JSON File')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('delimiter', models.CharField(default=',', max_length=10)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('has_header', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checksum_md5', models.CharField(blank=True, help_text='MD5 hash to detect duplicates', max_length=32, null=True)),
                ('retention_days', models.IntegerField(default=90)),
                ('is_archived', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('schema_version', models.IntegerField(default=1)),
                ('lineage_info', models.JSONField(blank=True, default=dict, help_text='Data provenance information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='ingestion.datasource')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'ingestion_datasource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Original row number in source file')),
                ('data', models.JSONField(help_text='Raw row data as JSON object')),
                ('data_hash', models.CharField(blank=True, help_text='Hash to detect duplicate rows', max_length=64, null=True)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('warning', 'Warning')], default='valid', max_length=20)),
                ('validation_messages', models.JSONField(blank=True, default=list)),
                ('partition_key', models.IntegerField(blank=True, help_text='For partitioning large datasets', null=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Is this a sample row?')),
                ('extraction_batch', models.IntegerField(blank=True, help_text='Batch processing ID', null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data_rows', to='ingestion.datasource')),
            ],
            options={
                'verbose_name': 'Raw Data',
                'verbose_name_plural': 'Raw Data',
                'db_table': 'ingestion_rawdata',
                'indexes': [models.Index(fields=['source', 'row_number'], name='ingestion_r_source__2badb0_idx')],
                'unique_together': {('source', 'row_number')},
            },
        ),
    ]
