# Generated by Django 6.0.3 on 2026-08-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestionjob_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('sheet_index', models.IntegerField(help_text='Order of the sheet in the workbook (0-based)')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('column_names', models.JSONField(blank=True, default=list, help_text='List of column names in this sheet')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sheet was imported')),
                ('quality_score', models.FloatField(blank=True, help_text='Auto-detected quality score (0-100)', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='Detected content type', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Source Sheet',
                'verbose_name_plural': 'Data Source Sheets',
                'db_table': 'ingestion_datasource_sheet',
                'ordering': ['sheet_index'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rawdata',
            name='ingestion_r_source__2badb0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='sheet_name',
            field=models.CharField(blank=True, default='', help_text='Sheet name for multi-sheet Excel files', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together={('source', 'sheet_name', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['source', 'sheet_name', 'row_number'], name='ingestion_r_source__4a5063_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['source', 'sheet_name'], name='ingestion_r_source__c34e64_idx'),
        ),
        migrations.AddField(
            model_name='datasourcesheet',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='ingestion.datasource'),
        ),
        migrations.AlterUniqueTogether(
            name='datasourcesheet',
            unique_together={('source', 'sheet_name')},
        ),
    ]
