# Generated by Django 6.0.3 on 2026-08-03 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_datasourcesheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(help_text="User-friendly name, e.g. 'client_commande'", max_length=200)),
                ('from_sheet', models.CharField(help_text='Source sheet name', max_length=255)),
                ('from_column', models.CharField(help_text='Source column (foreign key)', max_length=255)),
                ('to_sheet', models.CharField(help_text='Target sheet name', max_length=255)),
                ('to_column', models.CharField(help_text='Target column (primary key)', max_length=255)),
                ('join_type', models.CharField(choices=[('many_to_one', 'N:1 (Many-to-One)'), ('one_to_one', '1:1 (One-to-One)'), ('many_to_many', 'N:M (Many-to-Many)')], default='many_to_one', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0, help_text='Auto-detection confidence (0-1)')),
                ('match_ratio', models.FloatField(default=0.0, help_text='Ratio of values that match (0-1)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_relations', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_relations', to='ingestion.datasource')),
            ],
            options={
                'verbose_name': 'Sheet Relation',
                'verbose_name_plural': 'Sheet Relations',
                'db_table': 'ingestion_sheet_relation',
                'ordering': ['from_sheet', 'from_column'],
                'unique_together': {('source', 'from_sheet', 'from_column', 'to_sheet', 'to_column')},
            },
        ),
    ]
